### ISSUE TITLE
Handle fields with undeclared (assumed Object) type

### ISSUE THREAD

**Issue by jskov** [jskov/openapi-jaxrs-client#439]
bpm motor contains at least one type with fields that have no declared type.

Swagger editor treats these as (plain) Object.

Add option to allow same behavior - but disabled by default.
Fail in parsing if this is seen and the option is disabled.

```yaml
    AendringElement:
      required:
      - aendring
      type: object
      properties:
        aendring:
          description: Ændring som beskrevet i KRO API
          type: string
        oprindelig:
          description: Oprindelig værdi
        ny:
          description: Ønsket værdi
        valueType:
          description: Værdiens tekniske type (JAVA)
          type: string
```
