### ISSUE TITLE
Bad string escaping

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#543]
```yaml
ContactV2MergePatch:
      properties:
        email:
          description: Email address of the contact. Must comply with regex '^(?=.{1,64}@)[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(\.[A-Za-z]{2,})$'

 ```
Ends up as:

```java
  @JsonbProperty(JSON_PROPERTY_EMAIL)
  @Schema(nullable = true, description = "Email address of the contact. Must comply with regex '^(?=.{1,64}@)[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(\.[A-Za-z]{2,})$'", example = "jeka@virksomhed.dk")
  private String email;
 ```

which results in: Illegal escape character

(Martinsen)
