### ISSUE TITLE
Fields that are nullable but are also required generate bad code

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#606]
This schema contains `adresseId` which is both required and nullable:

```yaml
    AdresseIdentifikationDto:
      title: Adresseindentifikation
      required:
        - adgangsadresseId
        - adresseId
      type: object
      properties:
        adresseId:
          type: string
          format: uuid
          nullable: true
        adgangsadresseId:
          type: string
          format: uuid
      additionalProperties: false
```

The code generated is:

```java
  @JsonProperty(JSON_PROPERTY_ADRESSE_ID)
  @Schema(required = false, nullable = true)
  private UUID adresseId;
...

  @NotNull
  public UUID getAdresseId() {
    return adresseId;
  }
```

Deserialization fails when the field is present and null.

Should not be marked @NotNull, should have correct required=true+nullable=true in the @Schema

(Per)
