### ISSUE TITLE
Regression on Map value-type

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#615]
#611 introduced a regression:

Missing import for List:

```java
public class ValidationProblemDetails implements Serializable {
  public static final String JSON_PROPERTY_ERRORS = "errors";
  @JsonProperty(JSON_PROPERTY_ERRORS)
  private Map<String, List<String>> errors;
```

Comes from:

```yaml
    ValidationProblemDetails:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
```
(Per)
