### ISSUE TITLE
Discriminator needs to accept both references and schema names

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [jskov/openapi-jaxrs-client#845]
This:
```yaml
      discriminator:
        propertyName: nationalIdType
        mapping:
          PRIVATE:  GetPrivateSignerResponse
          COMPANY:  GetCompanySignerResponse
          FOREIGN:  GetForeignSignerResponse
```

Should be the same as this:
```yaml
      discriminator:
        propertyName: nationalIdType
        mapping:
          PRIVATE:  '#/components/schemas/GetPrivateSignerResponse'
          COMPANY:  '#/components/schemas/GetCompanySignerResponse'
          FOREIGN:  '#/components/schemas/GetForeignSignerResponse'
```

[An object to hold mappings between payload values and schema names or references.](https://spec.openapis.org/oas/v3.1.0#fixed-fields-20)

(Per, digitalSigning, postSignerRequest)
